# Generated by Django 4.2.15 on 2024-09-01 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='-', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IoS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.device')),
            ],
        ),
        migrations.CreateModel(
            name='IPVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.device')),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.ipversion'),
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=1000)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.device')),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.ipaddress')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.interfacetype')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('ios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.ios')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='ios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.ios'),
        ),
        migrations.AddField(
            model_name='device',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.devicerole'),
        ),
        migrations.AddField(
            model_name='device',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.deviceseries'),
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.site'),
        ),
    ]
