# Generated by Django 4.2.15 on 2024-09-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='interface',
            name='ip_address',
            field=models.ManyToManyField(to='info.ipaddress'),
        ),
    ]
