# Generated by Django 4.2.15 on 2024-09-14 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_interface_ip_address_interface_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='ip_address',
        ),
    ]
