# Generated by Django 4.2.15 on 2024-09-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_deviceseries_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicerole',
            name='description',
        ),
    ]
