# Generated by Django 4.2.15 on 2024-09-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_devicerole_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ios',
        ),
    ]
