# Generated by Django 4.2.15 on 2024-09-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_device_ios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceseries',
            name='ios',
        ),
        migrations.DeleteModel(
            name='IoS',
        ),
    ]
