# Generated by Django 4.2.15 on 2024-09-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_remove_device_role_remove_device_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.interface'),
        ),
    ]
