# Generated by Django 4.2.15 on 2024-09-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_ipaddress_interface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='status',
        ),
    ]
