# Generated by Django 4.2.15 on 2024-09-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_remove_ipaddress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vlan',
            name='ip_address',
        ),
    ]
