# Generated by Django 4.2.15 on 2024-09-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_remove_vlan_description_remove_vlan_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlan',
            old_name='id_number',
            new_name='vlan_id',
        ),
        migrations.RenameField(
            model_name='vlan',
            old_name='name',
            new_name='vlan_name',
        ),
    ]
