# Generated by Django 4.2.15 on 2024-10-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_vrfroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikrotikDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
            ],
        ),
    ]
