# Generated by Django 4.2.15 on 2024-10-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_mikrotikdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikrotikIPRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('gateway', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=255)),
                ('flag', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.mikrotikdevice')),
            ],
        ),
        migrations.CreateModel(
            name='MikrotikIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=255)),
                ('flag', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.mikrotikdevice')),
            ],
        ),
        migrations.CreateModel(
            name='MikrotikInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flag', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.mikrotikdevice')),
            ],
        ),
    ]
