# Generated by Django 4.2.15 on 2024-10-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_mikrotikiproute_mikrotikipaddress_mikrotikinterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikipaddress',
            name='interface',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
