# Generated by Django 4.2.15 on 2024-11-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_device_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikdevice',
            name='host_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
