# Generated by Django 4.2.15 on 2024-12-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_mikrotikdevice_host_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mikrotikinterface',
            name='device',
        ),
        migrations.RemoveField(
            model_name='mikrotikipaddress',
            name='device',
        ),
        migrations.RemoveField(
            model_name='mikrotikiproute',
            name='device',
        ),
        migrations.DeleteModel(
            name='MikrotikDevice',
        ),
        migrations.DeleteModel(
            name='MikrotikInterface',
        ),
        migrations.DeleteModel(
            name='MikrotikIPAddress',
        ),
        migrations.DeleteModel(
            name='MikrotikIPRoute',
        ),
    ]
